FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5000

# Regenerate Prisma client inside container
RUN npx prisma generate

# Deploy migrations
RUN npx prisma migrate deploy

CMD ["npm", "run", "dev"]
