FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Make start.sh executable
RUN chmod +x ./start.sh

EXPOSE 5000

# Regenerate Prisma client inside container
RUN npx prisma generate

CMD ["sh", "-c", "./start.sh"]
